# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_DTB_EXYNOS8910_STAR2LTE_KOR) := 	\
	exynos9810-star2lte_kor_16.dtb		\
	exynos9810-star2lte_kor_17.dtb		\
	exynos9810-star2lte_kor_18.dtb		\
	exynos9810-star2lte_kor_20.dtb		\
	exynos9810-star2lte_kor_23.dtb		\
	exynos9810-star2lte_kor_26.dtb

dtb-$(CONFIG_DTB_EXYNOS8910_STAR2LTE_EUR_OPEN) := 	\
	exynos9810-star2lte_eur_open_16.dtb		\
	exynos9810-star2lte_eur_open_17.dtb		\
	exynos9810-star2lte_eur_open_18.dtb		\
	exynos9810-star2lte_eur_open_20.dtb		\
	exynos9810-star2lte_eur_open_23.dtb		\
	exynos9810-star2lte_eur_open_26.dtb

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
